server:
  port: 8080
  servlet:

    context-path: 




    
spring:
  datasource:

    url: "jdbc:mysql://localhost:3306/qldoan"
    username: root
    password: nguyenlongnt2707
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect


jwt:
  secret: e66aef7ecf310f1d892779f5ce66963e0f5597de28416543eb6d4d63e12245fce5e9f64d3953a8e13f2259901efc99eb3a3ab7c1fa9dbddc1df29e4ce31ddc8a